listen_addresses = ['0.0.0.0:5053']
server_names = ['cloudflare-security']

require_dnssec = true
ipv6_servers = true

[sources]
  [sources.public-resolvers]
  url = 'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md'
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'

